// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnkhsarojoxpthjppavr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRua2hzYXJvam94cHRoanBwYXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjUxNjUsImV4cCI6MjA3MDM0MTE2NX0.vyaqa3_phXpV6xbYeuLcn5zg2nrtB5VVtEtC4QIgMW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});